FROM git.oncolog.ir:453/postgres
ENV POSTGRES_USER="pouriasa" POSTGRES_PASSWORD="4696048" POSTGRES_DB="consolex" AZ="Asia/Tehran" PGDATA="/var/lib/postgresql/data/pgdata"
RUN apt update && apt full-upgrade -y
